### PR TITLE
Maps Part 1

### PR DESCRIPTION
**Pull request by andreayang310**
Finished part 1 of maps, which includes creating a map and showing some landmarks. I wasn't sure what kind of map to make, but since we generalized the user group to college students, I just made the map centered at my university and added a few interesting places here. In the future that can be easily modified.
to access the page on the dev server, click on the Map link on the main page

### CODE REVIEW

**Review by mcardosog — CHANGES_REQUESTED** [review]
Over all the code looks perfect.
I will suggest create a .CSS and .JS files and separate it from the HTML. This will allow an easier use of the functionality without needed to repeat code.

**Review by mcardosog — APPROVED** [review]
Great it looks amazing!

**Comment by andreayang310** [comment]
Ah sorry I forgot to move the CSS earlier. It's up now!

**Review by mcardosog — APPROVED** [review]
Perfect

**Pull request merged**
